// RESTAURANTS
export const RESTAURANTS_LOADING = "RESTAURANTS_LOADING";
export const RESTAURANTS_DATA = "RESTAURANTS_DATA";
export const RESTAURANTS_ERROR = "RESTAURANTS_ERROR";

// LOCATIONS
export const LOCATIONS_LOADING = "LOCATIONS_LOADING";
export const LOCATIONS_DATA = "LOCATIONS_DATA";
export const LOCATIONS_ERROR = "LOCATIONS_ERROR";

// ADDRESS
export const ADDRESS_DATA = "ADDRESS_DATA";
export const ADDRESS_LOADING = "ADDRESS_LOADING";
export const ADDRESS_ERROR = "ADDRESS_ERROR";

// UPDATE
export const UPDATE_DATA = "UPDATE_DATA";
export const UPDATE_LOADING = "UPDATE_LOADING";
export const UPDATE_ERROR = "UPDATE_ERROR";

// PRE SEARCH
export const PRE_SEARCH_LOADING = "PRE_SEARCH_LOADING";
export const PRE_SEARCH_DATA = "PRE_SEARCH_DATA";
export const PRE_SEARCH_ERROR = "PRE_SEARCH_ERROR";

//SEARCHRESTAURANTS
export const SEARCHRESTAURANTS_LOADING = "SEARCHRESTAURANTS_LOADING";
export const SEARCHRESTAURANTS_DATA = "SEARCHRESTAURANTS_DATA";
export const SEARCHRESTAURANTS_ERROR = "SEARCHRESTAURANTS_ERROR";

//SINGLE_RESTAURANTS
export const SINGLE_RESTAURANTS_LOADING = "SINGLE_RESTAURANTS_LOADING";
export const SINGLE_RESTAURANTS_DATA = "SINGLE_RESTAURANTS_DATA";
export const SINGLE_RESTAURANTS_ERROR = "SINGLE_RESTAURANTS_ERROR";

// ADD TO CART
export const ADD_TO_CART = "ADD_TO_CART";

// FETCH RESTAURANT SEARCH DATA
export const ADD_SEARCH_RESTAURANT = "ADD_SEARCH_RESTAURANT";
export const LOADING_SEARCH_RESTAURANT = "LOADING_SEARCH_RESTAURANT";
export const ERROR_SEARCH_RESTAURANT = "ERROR_SEARCH_RESTAURANT";

// SIGN UP
export const LOADING_SIGNUP = "LOADING_SIGNUP";
export const ADD_SIGNUP = "ADD_SIGNUP";
export const ERROR_SIGNUP = "ERROR_SIGNUP";

// LOGIN
export const LOADING_LOGIN = "LOADING_LOGIN";
export const ADD_LOGIN = "ADD_LOGIN";
export const ERROR_LOGIN = "ERROR_LOGIN";

// OTP
export const LOADING_OTP = "LOADING_OTP";
export const ADD_OTP = "ADD_OTP";
export const ERROR_OTP = "ERROR_OTP";
